task {
  name: "Image classification"
  dataset {
    name: "Imagenet 2012"
    type: IMAGENET
    path: "/sdcard/mlperf_datasets/imagenet/img/"
    groundtruth_src: "@assets/imagenet_val.txt"
  }
  model {
    name: "MobileNetEdgeTPU 224 1.0 Int8"
    src: "https://github.com/mlperf/mobile_app/raw/model_repo_v0.7/tflite/mobilenet_edgetpu_224_1.0_int8.tflite"
    offset: 1
    tags: "int8"
  }
  model {
    name: "MobileNetEdgeTPU 224 1.0 F32"
    src: "https://github.com/mlperf/mobile_app/raw/model_repo_v0.7/tflite/mobilenet_edgetpu_224_1.0_float.tflite"
    offset: 1
    tags: "float32"
  }
  min_query_count: 100
  min_duration_ms: 1000
}

task {
  name: "Object detection"
  dataset {
    name: "Coco 2017"
    type: COCO
    path: "/sdcard/mlperf_datasets/coco/img/"
    groundtruth_src: "@assets/coco_val.pbtxt"
  }
  model {
    name: "SSD-MobileNets-v2 UInt8"
    src: "https://github.com/mlperf/mobile_app/raw/model_repo_v0.7/tflite/ssd_mobilenet_v2_300_uint8.tflite"
    offset: 1
    tags: "uint8"
  }
  model {
    name: "SSD-MobileNets-v2 F32"
    src: "https://github.com/mlperf/mobile_app/raw/model_repo_v0.7/tflite/ssd_mobilenet_v2_300_float.tflite"
    offset: 1
    tags: "float32"
  }
  min_query_count: 100
  min_duration_ms: 1000
}

task {
  name: " Language Understanding"
  dataset {
    name: "Dummy"
    type: MOBILEBERT
    path: "/sdcard/mlperf_datasets/mobilebert/"
  }
  model {
    name: "MobileBert F32"
    src: "https://github.com/mlperf/mobile_app/raw/model_repo_v0.7/tflite/mobilebert_float_20191023.tflite"
    tags: "float32"
  }
  min_query_count: 100
  min_duration_ms: 1000
}

task {
  name: "Image Segmentation"
  dataset {
    name: "ADE20k"
    type: ADE20K
    path: "/sdcard/mlperf_datasets/ade20k/"
  }

  model {
    name: "Deeplab-v3 Mobilenet-v2 F32"
    src: "https://github.com/mlperf/mobile_app/raw/model_repo_v0.7/tflite/deeplabv3_mnv2_ade20k_float.tflite"
    tags: "float32"
  }
  min_query_count: 100
  min_duration_ms: 1000
}
