task {
  name: "Image classification"
  dataset {
    name: "Imagenet 2012"
    type: IMAGENET
    path: "/sdcard/mlperf_datasets/imagenet/img/"
    groundtruth_src: "@assets/imagenet_val.txt"
  }
  model {
    name: "MobileNets-v1 224 Int8"
    src: "https://github.com/mlperf/mobile_app/raw/model_repo_v0.5/tflite/mobilenet_v1_224_full-integer.tflite"
    offset: 1
    tags: "int8"
  }
  model {
    name: "MobileNets-v1 224 F32"
    src: "https://github.com/mlperf/mobile_app/raw/model_repo_v0.5/tflite/mobilenet_v1_1.0_224.tflite"
    offset: 1
    tags: "float32"
  }
  min_query_count: 100
  min_duration_ms: 1000
}

task {
  name: "Object detection"
  dataset {
    name: "Coco 2017"
    type: COCO
    path: "/sdcard/mlperf_datasets/coco/img/"
    groundtruth_src: "@assets/coco_val.pbtxt"
  }
  model {
    name: "SSD-MobileNets-v1 Int8"
    src: "https://github.com/mlperf/mobile_app/raw/model_repo_v0.5/tflite/ssd_mobilenet_v1_300_full-integer.tflite"
    offset: 1
    tags: "int8"
  }
  model {
    name: "SSD-MobileNets-v1 F32"
    src: "https://github.com/mlperf/mobile_app/raw/model_repo_v0.5/tflite/ssd_mobilenet_v1_300_f32.tflite"
    offset: 1
    tags: "float32"
  }
  min_query_count: 100
  min_duration_ms: 1000
}
